language: python

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/Library/Caches/Homebrew
    - $HOME/HomebrewLocal
    - $HOME/.ccache
    - /Library/Caches/Homebrew
    - $HOME/Library/Caches/pip/wheels
    - /Library/Caches/pip/wheels

# So commits do not get built twice.
# Only test master and tagged releases on push
#   always test things that aren't pushes (like PRs)
if: type != push OR branch = master OR branch =~ /^\d+\.\d+(\.\d+)?(-\S*)?$/ OR tag ~= /^\d+\.\d+(\.\d+)?(.\S*)?$/


matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
      python: 2.7
    - os: linux
      sudo: required
      dist: xenial
      python: 3.5
    - os: linux
      sudo: required
      dist: xenial
      python: 3.6
    - os: linux
      sudo: required
      python: 3.7
      dist: xenial

    # pypy build is broken. The pypy on travis is really old.
    # - os: linux
    #   sudo: required
    #   python: pypy

    # Should only need one OSX build because older builds can work on newer machines ok.
    #https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PY_VERSION=3
        - PY_VERSION_=3.7
        - MAKEFLAGS=-j8
        - GITHUB_UPLOAD=yes
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PY_VERSION=2
        - MAKEFLAGS=-j8
        - GITHUB_UPLOAD=yes
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PY_VERSION=3
        - PY_VERSION_=3.6
        - MAKEFLAGS=-j8
        - GITHUB_UPLOAD=yes
    # - os: osx
    #   osx_image: xcode7.3
    #   language: generic
    #   env:
    #     - PY_VERSION=pypy3
    #     - MAKEFLAGS=-j8
    # - os: osx
    #   osx_image: xcode7.3
    #   language: generic
    #   env:
    #     - PY_VERSION=pypy2
    #     - MAKEFLAGS=-j8
    #     # - MACOSX_DEPLOYMENT_TARGET=10.6


  allow_failures:
    - python: pypy
    - os: osx
      env: PY_VERSION=pypy2
    - os: osx
      env: PY_VERSION=pypy3

before_install:
  - export PATH=/usr/lib/ccache:$PATH
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source buildconfig/ci/travis/.travis_osx_before_install.sh;  fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update
      sudo apt-get install python-dev libsdl-image1.2-dev libsdl-mixer1.2-dev \
        libsdl-ttf2.0-dev libsdl1.2-dev python-numpy libportmidi-dev libjpeg-dev \
        libtiff5-dev libx11-6 libx11-dev xfonts-base xfonts-100dpi xfonts-75dpi \
        xfonts-cyrillic fluid-soundfont-gm musescore-soundfont-gm
    fi
install:
  - "python buildconfig/ci/travis/.travis_osx_upload_whl.py --write-config"
  - $(set | grep PYPI_ | python -c "import sys;print('\n'.join(['unset %s' % l.split('=')[0] for l in sys.stdin.readlines() if l.startswith('PYPI')]))")
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source buildconfig/ci/travis/.travis_osx.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then PYTHON_EXE=python PIP_CMD=pip; fi
  - "$PIP_CMD install --upgrade pip"
  - "$PIP_CMD install --upgrade numpy"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then $PIP_CMD install delocate twine; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then $PYTHON_EXE setup.py install -noheaders -auto; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source buildconfig/ci/travis/.travis_osx_install.sh; fi
env:
  global:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=disk
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then $(set | grep PYPI_ | python -c "import sys;print('\n'.join(['unset %s' % l.split('=')[0] for l in sys.stdin.readlines() if l.startswith('PYPI')]))"); fi
  - $PYTHON_EXE -m pygame.tests.__main__ --exclude opengl --time_out 300

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source buildconfig/ci/travis/.travis_osx_after_success.sh; fi

after_script:
  - rm -f .travis_tmp

deploy:
  # https://docs.travis-ci.com/user/deployment/releases/
  - provider: releases
    api_key:
      secure: NyaCDB9oKIuM78ZzbSqdvXjJoOFYmFHCcrRHrigMJOQPMhQ//2M/pOrT2IT+u49z9X1YrqapZEPVQLAXoSf66vraGKcBDfePfzHcd7BzQCXzRIPJabSti4pRRf3hmtHTLXDyQXDTDOokNQIYUSHQM5DwxOPkdYrDuJsKcdZYb9ZLs3A4SGZG9xcKTXPHZSVDZW0j3/nLtdnv2RFL9gEaj7Z6MmZsXGGEeu6dkylx1ySC49VZR2xssdTnkYMRYYL25oqOk98MC4jKJsPXqI7VHc6qwtIDfIQ9ZbUGyD4ZyqHaaiCr50ifUTLmnlusTPb/pQd6qN8RQDkpknxs0hD9WhhRxVcMY6OJB3VyxKSvkeV3YusYQEWpnI5sidSMF6kGI9kajGMGk0QDtoTqmtq8P0rnttmARDG1HLdM3xMX3VFh7y6SkxLhMPBEsDrR+y2pw7DUUK5joOY+LZXl7hbTZmn/O1u39wPUmkNfkomdKwWzf+6PH14qNUxecZj2xf/G/RZnOOuzh79cJeD0G21WC9IBdcJrea6OqCEjwS+w2ynFyxeww4Bp/1q3jiXVpPr4ZNsd5sfFdgiG2FCcSWnXCbEWaM5OYrZ7Vo8r5/T+d4F3rEiBTDsG2fynEc8nSDXMMPCRi2NSc3pljrVW/ZSkfSVx8xyNqv04FRZYphwL4pc=
    file_glob: true
    file:
      - dist/*.whl
    skip_cleanup: true
    draft: true
    on:
      all_branches: true
      # branches:
      #   only:
      #     - master
      tag: true
      repo: cartr/pygame-polite
      condition: $GITHUB_UPLOAD = yes
